### PR TITLE
OBDB-62 - Updating Sort param with asc and desc values

### PR DESCRIPTION
**Pull request by Johnnyk737**
# Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests pass (`bundle exec rake`)
- [x] CHANGELOG.md updated

Doc update: https://github.com/openbrewerydb/openbrewerydb-gatsby/pull/43

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## Current behavior

Issue Number: https://github.com/openbrewerydb/openbrewerydb-rails-api/issues/62

## New behavior
We are fixing the sort parameter to be more clear on what sorting will be applied to each field. The new sort parameter will accept comma separated values each formatted like `field:sort`. The old way of `+/-field` is not going to work and is going to default to `asc`

## Does this introduce a breaking change

- [x] Yes
- [ ] No

The new sort parameter will accept comma separated values each formatted like `field:sort`. The old way of `+/-field` is not going to work and is going to default to `asc`

### Testing
URL: http://localhost:3000/breweries?by_city=san_diego&sort=type,name:asc

Rspec
image

### CODE REVIEW

**Comment by Johnnyk737** [comment]
We need to update our documentation before this PR is merged, and notify the consumers as this is a breaking change for sorting.

**Comment by chrisjm** [comment]
You're awesome, @Johnnyk737 ! I should have some time to review and test this evening. 

Good point about notifying about breaking changes! (I'm typically more cowboy about releases :) ) I figure the best way to do this is via the newsletter. I think it'll also be worth warning about changes coming in issue #31 . 

How long do you think we should wait after notification to merge and deploy this change?

**Comment by Johnnyk737** [comment]
> How long do you think we should wait after notification to merge and deploy this change?

That is a good question. I think 5-7 days would be plenty of time. It's long enough that people who are even mildly active on Discord will be able to see the notification.

**Comment by chrisjm** [comment]
Newsletter and announcement in Discord sent! Let's merge this on Wednesday 5/19! 🎉 🍻  I know, far less than 5-7 days, but I don't think we'll hear any objections.

And if you (the reader) do have objections, please speak up now! We're cowboy-ing this! 🤠

**Comment by Johnnyk737** [comment]
Yee haw! Lets do this!

**Comment by Johnnyk737** [comment]
@chrisjm Mind re-reviewing this when you get a chance?

**Comment by chrisjm** [comment]
OMG! Thanks for the ping @Johnnyk737 ! I totally forgot about this! 🤦 

Merged! 🍻

**Pull request merged**
